### ISSUE TITLE
Was checking out your book

### ISSUE THREAD

**Issue by LedLoaf** [fkhydra/direct2d_nutshell#1]
Hello,

I was checking out your book and came here. I'm a bit confused, what version is this Direct2D related too? Is this DirectX9? I did some brief searching and they said Direct2D uses DirectX11 and if so that is awesome to here.

Thanks

**Comment by fkhydra** [comment]
Hi,

thanks for the question.

Direct2D is part of DirectX, that's right. D2D is available since Windows Vista with Service Pack 2, so I wouldn't go lower than the DirectX version 10.1, when it comes to programming.

D2D has it's own versioning too, which has nothing to do with the DX versioning.

I hope, it helped.

Krisztián

**Comment by fkhydra** [comment]
Just a short remark: every up to date DirectX versions support Direct2D.
